### ISSUE TITLE
Реализовать EJBBeansGateway

### ISSUE THREAD

**Issue by dromenskyi** [dromenskyi/nc.edu.group8.lb4#5]
Написать реализацию гейтвей для работы с бинами. Файл  module-web / src / main / java / hibernate / dao / EJBBeansGateway.java

**Comment by hdls** [comment]
а есть какойто пример как это делать? :)

**Comment by dromenskyi** [comment]
http://www.intuit.ru/studies/courses/571/427/info

здесь почитай, довольно объемно написано

**Comment by dromenskyi** [comment]
remove в хоум интерфейсе наследуется от EJBHome.remove(Object primaryKey) - http://docs.oracle.com/javaee/6/api/javax/ejb/EJBHome.html Его по ходу вообще не надо имплементить

по поводу гейтвея - в методе get() копипаста подвела :) там не с entity нада работать а с className

**Comment by hdls** [comment]
стектрейс ошибки

2014-04-12 11:39:08,920 ERRORfault (self-tuning)'.dao.EJBBeansGateway - Connecti
on problems. Ensure that weblogic is running
java.rmi.RemoteException: Exception in ejbFindAll; nested exception is:
        java.lang.NullPointerException
        at weblogic.ejb.container.internal.EJBRuntimeUtils.throwRemoteException(
EJBRuntimeUtils.java:104)
        at weblogic.ejb.container.internal.BaseRemoteObject.handleSystemExceptio
n(BaseRemoteObject.java:530)
        at weblogic.ejb.container.internal.BaseEJBHome.handleSystemException(Bas
eEJBHome.java:309)
        at weblogic.ejb.container.internal.EntityEJBHome.finder(EntityEJBHome.ja
va:1098)
        at beans.country.CountryBean_yiiif4_HomeImpl.findAll(CountryBean_yiiif4_
HomeImpl.java:97)
        at hibernate.dao.EJBBeansGateway.getAll(EJBBeansGateway.java:331)
        at action.handlers.country.ShowAllCountry.perform(ShowAllCountry.java:30
)
        at servlet.ServletPrototype.service(ServletPrototype.java:21)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:844)
        at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run
(StubSecurityHelper.java:280)
        at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run
(StubSecurityHelper.java:254)
        at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecuri
tyHelper.java:136)
        at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.jav
a:341)
        at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.jav
a:238)
        at weblogic.servlet.internal.WebAppServletContext$ServletInvocationActio
n.wrapRun(WebAppServletContext.java:3363)
        at weblogic.servlet.internal.WebAppServletContext$ServletInvocationActio
n.run(WebAppServletContext.java:3333)
        at weblogic.security.acl.internal.AuthenticatedSubject.doAs(Authenticate
dSubject.java:321)
        at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:
120)
        at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:
57)
        at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAp
pServletContext.java:2220)
        at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppS
ervletContext.java:2146)
        at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletC
ontext.java:2124)
        at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.j
ava:1564)
        at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExec
utor.run(ContainerSupportProviderImpl.java:254)
        at weblogic.work.ExecuteThread.execute(ExecuteThread.java:295)
        at weblogic.work.ExecuteThread.run(ExecuteThread.java:254)
Caused by: java.lang.NullPointerException
        at util.DBTool.getConnection(DBTool.java:38)
        at beans.country.CountryBean.selectAll(CountryBean.java:282)
        at beans.country.CountryBean.ejbFindAll(CountryBean.java:141)
        at beans.country.CountryBean_yiiif4_Impl.ejbFindAll(CountryBean_yiiif4_I
mpl.java:214)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at weblogic.ejb.container.manager.BeanManagedPersistenceManager.collecti
onFinder(BeanManagedPersistenceManager.java:149)
        at weblogic.ejb.container.manager.BaseEntityManager.collectionFinder(Bas
eEntityManager.java:2709)
        at weblogic.ejb.container.manager.BaseEntityManager.collectionFinder(Bas
eEntityManager.java:2685)
        at weblogic.ejb.container.internal.EntityEJBHome.finder(EntityEJBHome.ja
va:1088)
        ... 22 more
